# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rexample.proto\x12\x07\x65xample\"\xbf\x02\n\x04\x44\x61ta\x12#\n\x06graphs\x18\x05 \x03(\x0b\x32\x13.example.Data.Graph\x1a\x91\x02\n\x05Graph\x12\r\n\x05right\x18\x01 \x02(\x05\x12\'\n\x05nodes\x18\x03 \x03(\x0b\x32\x18.example.Data.Graph.Node\x12\x0b\n\x03opt\x18\x07 \x02(\x05\x12\x16\n\x0elearned_switch\x18\x08 \x02(\x05\x12\x1c\n\x14learned_leftest_node\x18\t \x02(\x05\x12\x12\n\nbarycenter\x18\n \x02(\x05\x12\x15\n\rgreedy_insert\x18\x0b \x02(\x05\x12\x15\n\rgreedy_switch\x18\x0c \x02(\x05\x12\x0e\n\x06median\x18\r \x02(\x05\x12\x0f\n\x07sifting\x18\x0e \x02(\x05\x12\r\n\x05split\x18\x0f \x02(\x05\x1a\x1b\n\x04Node\x12\x13\n\x0b\x63onnectedto\x18\x02 \x03(\x05'
)




_DATA_GRAPH_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='example.Data.Graph.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectedto', full_name='example.Data.Graph.Node.connectedto', index=0,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=346,
)

_DATA_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='example.Data.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='right', full_name='example.Data.Graph.right', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='example.Data.Graph.nodes', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt', full_name='example.Data.Graph.opt', index=2,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learned_switch', full_name='example.Data.Graph.learned_switch', index=3,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learned_leftest_node', full_name='example.Data.Graph.learned_leftest_node', index=4,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barycenter', full_name='example.Data.Graph.barycenter', index=5,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='greedy_insert', full_name='example.Data.Graph.greedy_insert', index=6,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='greedy_switch', full_name='example.Data.Graph.greedy_switch', index=7,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='median', full_name='example.Data.Graph.median', index=8,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sifting', full_name='example.Data.Graph.sifting', index=9,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='split', full_name='example.Data.Graph.split', index=10,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_GRAPH_NODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=346,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='example.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphs', full_name='example.Data.graphs', index=0,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_GRAPH, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=346,
)

_DATA_GRAPH_NODE.containing_type = _DATA_GRAPH
_DATA_GRAPH.fields_by_name['nodes'].message_type = _DATA_GRAPH_NODE
_DATA_GRAPH.containing_type = _DATA
_DATA.fields_by_name['graphs'].message_type = _DATA_GRAPH
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {

  'Graph' : _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {

    'Node' : _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
      'DESCRIPTOR' : _DATA_GRAPH_NODE,
      '__module__' : 'example_pb2'
      # @@protoc_insertion_point(class_scope:example.Data.Graph.Node)
      })
    ,
    'DESCRIPTOR' : _DATA_GRAPH,
    '__module__' : 'example_pb2'
    # @@protoc_insertion_point(class_scope:example.Data.Graph)
    })
  ,
  'DESCRIPTOR' : _DATA,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.Data)
  })
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.Graph)
_sym_db.RegisterMessage(Data.Graph.Node)


# @@protoc_insertion_point(module_scope)
