// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_example_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_example_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_example_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_example_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_example_2eproto;
namespace example {
class Data;
class DataDefaultTypeInternal;
extern DataDefaultTypeInternal _Data_default_instance_;
class Data_Graph;
class Data_GraphDefaultTypeInternal;
extern Data_GraphDefaultTypeInternal _Data_Graph_default_instance_;
class Data_Graph_Node;
class Data_Graph_NodeDefaultTypeInternal;
extern Data_Graph_NodeDefaultTypeInternal _Data_Graph_Node_default_instance_;
}  // namespace example
PROTOBUF_NAMESPACE_OPEN
template<> ::example::Data* Arena::CreateMaybeMessage<::example::Data>(Arena*);
template<> ::example::Data_Graph* Arena::CreateMaybeMessage<::example::Data_Graph>(Arena*);
template<> ::example::Data_Graph_Node* Arena::CreateMaybeMessage<::example::Data_Graph_Node>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace example {

// ===================================================================

class Data_Graph_Node :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example.Data.Graph.Node) */ {
 public:
  Data_Graph_Node();
  virtual ~Data_Graph_Node();

  Data_Graph_Node(const Data_Graph_Node& from);
  Data_Graph_Node(Data_Graph_Node&& from) noexcept
    : Data_Graph_Node() {
    *this = ::std::move(from);
  }

  inline Data_Graph_Node& operator=(const Data_Graph_Node& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data_Graph_Node& operator=(Data_Graph_Node&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Data_Graph_Node& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data_Graph_Node* internal_default_instance() {
    return reinterpret_cast<const Data_Graph_Node*>(
               &_Data_Graph_Node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Data_Graph_Node& a, Data_Graph_Node& b) {
    a.Swap(&b);
  }
  inline void Swap(Data_Graph_Node* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Data_Graph_Node* New() const final {
    return CreateMaybeMessage<Data_Graph_Node>(nullptr);
  }

  Data_Graph_Node* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Data_Graph_Node>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Data_Graph_Node& from);
  void MergeFrom(const Data_Graph_Node& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data_Graph_Node* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example.Data.Graph.Node";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_example_2eproto);
    return ::descriptor_table_example_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConnectedtoFieldNumber = 2,
  };
  // repeated int32 connectedto = 2;
  int connectedto_size() const;
  private:
  int _internal_connectedto_size() const;
  public:
  void clear_connectedto();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_connectedto(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_connectedto() const;
  void _internal_add_connectedto(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_connectedto();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 connectedto(int index) const;
  void set_connectedto(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_connectedto(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      connectedto() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_connectedto();

  // @@protoc_insertion_point(class_scope:example.Data.Graph.Node)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > connectedto_;
  friend struct ::TableStruct_example_2eproto;
};
// -------------------------------------------------------------------

class Data_Graph :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example.Data.Graph) */ {
 public:
  Data_Graph();
  virtual ~Data_Graph();

  Data_Graph(const Data_Graph& from);
  Data_Graph(Data_Graph&& from) noexcept
    : Data_Graph() {
    *this = ::std::move(from);
  }

  inline Data_Graph& operator=(const Data_Graph& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data_Graph& operator=(Data_Graph&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Data_Graph& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data_Graph* internal_default_instance() {
    return reinterpret_cast<const Data_Graph*>(
               &_Data_Graph_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Data_Graph& a, Data_Graph& b) {
    a.Swap(&b);
  }
  inline void Swap(Data_Graph* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Data_Graph* New() const final {
    return CreateMaybeMessage<Data_Graph>(nullptr);
  }

  Data_Graph* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Data_Graph>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Data_Graph& from);
  void MergeFrom(const Data_Graph& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data_Graph* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example.Data.Graph";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_example_2eproto);
    return ::descriptor_table_example_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Data_Graph_Node Node;

  // accessors -------------------------------------------------------

  enum : int {
    kNodesFieldNumber = 3,
    kRightFieldNumber = 1,
    kOptFieldNumber = 7,
    kLearnedSwitchFieldNumber = 8,
    kLearnedLeftestNodeFieldNumber = 9,
    kBarycenterFieldNumber = 10,
    kGreedyInsertFieldNumber = 11,
    kGreedySwitchFieldNumber = 12,
    kMedianFieldNumber = 13,
    kSiftingFieldNumber = 14,
    kSplitFieldNumber = 15,
  };
  // repeated .example.Data.Graph.Node nodes = 3;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  ::example::Data_Graph_Node* mutable_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph_Node >*
      mutable_nodes();
  private:
  const ::example::Data_Graph_Node& _internal_nodes(int index) const;
  ::example::Data_Graph_Node* _internal_add_nodes();
  public:
  const ::example::Data_Graph_Node& nodes(int index) const;
  ::example::Data_Graph_Node* add_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph_Node >&
      nodes() const;

  // required int32 right = 1;
  bool has_right() const;
  private:
  bool _internal_has_right() const;
  public:
  void clear_right();
  ::PROTOBUF_NAMESPACE_ID::int32 right() const;
  void set_right(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_right() const;
  void _internal_set_right(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 opt = 7;
  bool has_opt() const;
  private:
  bool _internal_has_opt() const;
  public:
  void clear_opt();
  ::PROTOBUF_NAMESPACE_ID::int32 opt() const;
  void set_opt(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_opt() const;
  void _internal_set_opt(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 learned_switch = 8;
  bool has_learned_switch() const;
  private:
  bool _internal_has_learned_switch() const;
  public:
  void clear_learned_switch();
  ::PROTOBUF_NAMESPACE_ID::int32 learned_switch() const;
  void set_learned_switch(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_learned_switch() const;
  void _internal_set_learned_switch(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 learned_leftest_node = 9;
  bool has_learned_leftest_node() const;
  private:
  bool _internal_has_learned_leftest_node() const;
  public:
  void clear_learned_leftest_node();
  ::PROTOBUF_NAMESPACE_ID::int32 learned_leftest_node() const;
  void set_learned_leftest_node(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_learned_leftest_node() const;
  void _internal_set_learned_leftest_node(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 barycenter = 10;
  bool has_barycenter() const;
  private:
  bool _internal_has_barycenter() const;
  public:
  void clear_barycenter();
  ::PROTOBUF_NAMESPACE_ID::int32 barycenter() const;
  void set_barycenter(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_barycenter() const;
  void _internal_set_barycenter(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 greedy_insert = 11;
  bool has_greedy_insert() const;
  private:
  bool _internal_has_greedy_insert() const;
  public:
  void clear_greedy_insert();
  ::PROTOBUF_NAMESPACE_ID::int32 greedy_insert() const;
  void set_greedy_insert(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_greedy_insert() const;
  void _internal_set_greedy_insert(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 greedy_switch = 12;
  bool has_greedy_switch() const;
  private:
  bool _internal_has_greedy_switch() const;
  public:
  void clear_greedy_switch();
  ::PROTOBUF_NAMESPACE_ID::int32 greedy_switch() const;
  void set_greedy_switch(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_greedy_switch() const;
  void _internal_set_greedy_switch(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 median = 13;
  bool has_median() const;
  private:
  bool _internal_has_median() const;
  public:
  void clear_median();
  ::PROTOBUF_NAMESPACE_ID::int32 median() const;
  void set_median(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_median() const;
  void _internal_set_median(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 sifting = 14;
  bool has_sifting() const;
  private:
  bool _internal_has_sifting() const;
  public:
  void clear_sifting();
  ::PROTOBUF_NAMESPACE_ID::int32 sifting() const;
  void set_sifting(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sifting() const;
  void _internal_set_sifting(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 split = 15;
  bool has_split() const;
  private:
  bool _internal_has_split() const;
  public:
  void clear_split();
  ::PROTOBUF_NAMESPACE_ID::int32 split() const;
  void set_split(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_split() const;
  void _internal_set_split(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:example.Data.Graph)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph_Node > nodes_;
  ::PROTOBUF_NAMESPACE_ID::int32 right_;
  ::PROTOBUF_NAMESPACE_ID::int32 opt_;
  ::PROTOBUF_NAMESPACE_ID::int32 learned_switch_;
  ::PROTOBUF_NAMESPACE_ID::int32 learned_leftest_node_;
  ::PROTOBUF_NAMESPACE_ID::int32 barycenter_;
  ::PROTOBUF_NAMESPACE_ID::int32 greedy_insert_;
  ::PROTOBUF_NAMESPACE_ID::int32 greedy_switch_;
  ::PROTOBUF_NAMESPACE_ID::int32 median_;
  ::PROTOBUF_NAMESPACE_ID::int32 sifting_;
  ::PROTOBUF_NAMESPACE_ID::int32 split_;
  friend struct ::TableStruct_example_2eproto;
};
// -------------------------------------------------------------------

class Data :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:example.Data) */ {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);
  Data(Data&& from) noexcept
    : Data() {
    *this = ::std::move(from);
  }

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Data& operator=(Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data* internal_default_instance() {
    return reinterpret_cast<const Data*>(
               &_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Data& a, Data& b) {
    a.Swap(&b);
  }
  inline void Swap(Data* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Data* New() const final {
    return CreateMaybeMessage<Data>(nullptr);
  }

  Data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Data>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "example.Data";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_example_2eproto);
    return ::descriptor_table_example_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Data_Graph Graph;

  // accessors -------------------------------------------------------

  enum : int {
    kGraphsFieldNumber = 5,
  };
  // repeated .example.Data.Graph graphs = 5;
  int graphs_size() const;
  private:
  int _internal_graphs_size() const;
  public:
  void clear_graphs();
  ::example::Data_Graph* mutable_graphs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph >*
      mutable_graphs();
  private:
  const ::example::Data_Graph& _internal_graphs(int index) const;
  ::example::Data_Graph* _internal_add_graphs();
  public:
  const ::example::Data_Graph& graphs(int index) const;
  ::example::Data_Graph* add_graphs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph >&
      graphs() const;

  // @@protoc_insertion_point(class_scope:example.Data)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph > graphs_;
  friend struct ::TableStruct_example_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Data_Graph_Node

// repeated int32 connectedto = 2;
inline int Data_Graph_Node::_internal_connectedto_size() const {
  return connectedto_.size();
}
inline int Data_Graph_Node::connectedto_size() const {
  return _internal_connectedto_size();
}
inline void Data_Graph_Node::clear_connectedto() {
  connectedto_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph_Node::_internal_connectedto(int index) const {
  return connectedto_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph_Node::connectedto(int index) const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.Node.connectedto)
  return _internal_connectedto(index);
}
inline void Data_Graph_Node::set_connectedto(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  connectedto_.Set(index, value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.Node.connectedto)
}
inline void Data_Graph_Node::_internal_add_connectedto(::PROTOBUF_NAMESPACE_ID::int32 value) {
  connectedto_.Add(value);
}
inline void Data_Graph_Node::add_connectedto(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_connectedto(value);
  // @@protoc_insertion_point(field_add:example.Data.Graph.Node.connectedto)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Data_Graph_Node::_internal_connectedto() const {
  return connectedto_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Data_Graph_Node::connectedto() const {
  // @@protoc_insertion_point(field_list:example.Data.Graph.Node.connectedto)
  return _internal_connectedto();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Data_Graph_Node::_internal_mutable_connectedto() {
  return &connectedto_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Data_Graph_Node::mutable_connectedto() {
  // @@protoc_insertion_point(field_mutable_list:example.Data.Graph.Node.connectedto)
  return _internal_mutable_connectedto();
}

// -------------------------------------------------------------------

// Data_Graph

// required int32 right = 1;
inline bool Data_Graph::_internal_has_right() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Data_Graph::has_right() const {
  return _internal_has_right();
}
inline void Data_Graph::clear_right() {
  right_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_right() const {
  return right_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::right() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.right)
  return _internal_right();
}
inline void Data_Graph::_internal_set_right(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  right_ = value;
}
inline void Data_Graph::set_right(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.right)
}

// repeated .example.Data.Graph.Node nodes = 3;
inline int Data_Graph::_internal_nodes_size() const {
  return nodes_.size();
}
inline int Data_Graph::nodes_size() const {
  return _internal_nodes_size();
}
inline void Data_Graph::clear_nodes() {
  nodes_.Clear();
}
inline ::example::Data_Graph_Node* Data_Graph::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:example.Data.Graph.nodes)
  return nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph_Node >*
Data_Graph::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:example.Data.Graph.nodes)
  return &nodes_;
}
inline const ::example::Data_Graph_Node& Data_Graph::_internal_nodes(int index) const {
  return nodes_.Get(index);
}
inline const ::example::Data_Graph_Node& Data_Graph::nodes(int index) const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.nodes)
  return _internal_nodes(index);
}
inline ::example::Data_Graph_Node* Data_Graph::_internal_add_nodes() {
  return nodes_.Add();
}
inline ::example::Data_Graph_Node* Data_Graph::add_nodes() {
  // @@protoc_insertion_point(field_add:example.Data.Graph.nodes)
  return _internal_add_nodes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph_Node >&
Data_Graph::nodes() const {
  // @@protoc_insertion_point(field_list:example.Data.Graph.nodes)
  return nodes_;
}

// required int32 opt = 7;
inline bool Data_Graph::_internal_has_opt() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Data_Graph::has_opt() const {
  return _internal_has_opt();
}
inline void Data_Graph::clear_opt() {
  opt_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_opt() const {
  return opt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::opt() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.opt)
  return _internal_opt();
}
inline void Data_Graph::_internal_set_opt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  opt_ = value;
}
inline void Data_Graph::set_opt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_opt(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.opt)
}

// required int32 learned_switch = 8;
inline bool Data_Graph::_internal_has_learned_switch() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Data_Graph::has_learned_switch() const {
  return _internal_has_learned_switch();
}
inline void Data_Graph::clear_learned_switch() {
  learned_switch_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_learned_switch() const {
  return learned_switch_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::learned_switch() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.learned_switch)
  return _internal_learned_switch();
}
inline void Data_Graph::_internal_set_learned_switch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  learned_switch_ = value;
}
inline void Data_Graph::set_learned_switch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_learned_switch(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.learned_switch)
}

// required int32 learned_leftest_node = 9;
inline bool Data_Graph::_internal_has_learned_leftest_node() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Data_Graph::has_learned_leftest_node() const {
  return _internal_has_learned_leftest_node();
}
inline void Data_Graph::clear_learned_leftest_node() {
  learned_leftest_node_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_learned_leftest_node() const {
  return learned_leftest_node_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::learned_leftest_node() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.learned_leftest_node)
  return _internal_learned_leftest_node();
}
inline void Data_Graph::_internal_set_learned_leftest_node(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  learned_leftest_node_ = value;
}
inline void Data_Graph::set_learned_leftest_node(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_learned_leftest_node(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.learned_leftest_node)
}

// required int32 barycenter = 10;
inline bool Data_Graph::_internal_has_barycenter() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Data_Graph::has_barycenter() const {
  return _internal_has_barycenter();
}
inline void Data_Graph::clear_barycenter() {
  barycenter_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_barycenter() const {
  return barycenter_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::barycenter() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.barycenter)
  return _internal_barycenter();
}
inline void Data_Graph::_internal_set_barycenter(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  barycenter_ = value;
}
inline void Data_Graph::set_barycenter(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_barycenter(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.barycenter)
}

// required int32 greedy_insert = 11;
inline bool Data_Graph::_internal_has_greedy_insert() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Data_Graph::has_greedy_insert() const {
  return _internal_has_greedy_insert();
}
inline void Data_Graph::clear_greedy_insert() {
  greedy_insert_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_greedy_insert() const {
  return greedy_insert_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::greedy_insert() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.greedy_insert)
  return _internal_greedy_insert();
}
inline void Data_Graph::_internal_set_greedy_insert(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  greedy_insert_ = value;
}
inline void Data_Graph::set_greedy_insert(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_greedy_insert(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.greedy_insert)
}

// required int32 greedy_switch = 12;
inline bool Data_Graph::_internal_has_greedy_switch() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Data_Graph::has_greedy_switch() const {
  return _internal_has_greedy_switch();
}
inline void Data_Graph::clear_greedy_switch() {
  greedy_switch_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_greedy_switch() const {
  return greedy_switch_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::greedy_switch() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.greedy_switch)
  return _internal_greedy_switch();
}
inline void Data_Graph::_internal_set_greedy_switch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  greedy_switch_ = value;
}
inline void Data_Graph::set_greedy_switch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_greedy_switch(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.greedy_switch)
}

// required int32 median = 13;
inline bool Data_Graph::_internal_has_median() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Data_Graph::has_median() const {
  return _internal_has_median();
}
inline void Data_Graph::clear_median() {
  median_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_median() const {
  return median_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::median() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.median)
  return _internal_median();
}
inline void Data_Graph::_internal_set_median(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000080u;
  median_ = value;
}
inline void Data_Graph::set_median(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_median(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.median)
}

// required int32 sifting = 14;
inline bool Data_Graph::_internal_has_sifting() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Data_Graph::has_sifting() const {
  return _internal_has_sifting();
}
inline void Data_Graph::clear_sifting() {
  sifting_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_sifting() const {
  return sifting_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::sifting() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.sifting)
  return _internal_sifting();
}
inline void Data_Graph::_internal_set_sifting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000100u;
  sifting_ = value;
}
inline void Data_Graph::set_sifting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sifting(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.sifting)
}

// required int32 split = 15;
inline bool Data_Graph::_internal_has_split() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Data_Graph::has_split() const {
  return _internal_has_split();
}
inline void Data_Graph::clear_split() {
  split_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::_internal_split() const {
  return split_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Data_Graph::split() const {
  // @@protoc_insertion_point(field_get:example.Data.Graph.split)
  return _internal_split();
}
inline void Data_Graph::_internal_set_split(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000200u;
  split_ = value;
}
inline void Data_Graph::set_split(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_split(value);
  // @@protoc_insertion_point(field_set:example.Data.Graph.split)
}

// -------------------------------------------------------------------

// Data

// repeated .example.Data.Graph graphs = 5;
inline int Data::_internal_graphs_size() const {
  return graphs_.size();
}
inline int Data::graphs_size() const {
  return _internal_graphs_size();
}
inline void Data::clear_graphs() {
  graphs_.Clear();
}
inline ::example::Data_Graph* Data::mutable_graphs(int index) {
  // @@protoc_insertion_point(field_mutable:example.Data.graphs)
  return graphs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph >*
Data::mutable_graphs() {
  // @@protoc_insertion_point(field_mutable_list:example.Data.graphs)
  return &graphs_;
}
inline const ::example::Data_Graph& Data::_internal_graphs(int index) const {
  return graphs_.Get(index);
}
inline const ::example::Data_Graph& Data::graphs(int index) const {
  // @@protoc_insertion_point(field_get:example.Data.graphs)
  return _internal_graphs(index);
}
inline ::example::Data_Graph* Data::_internal_add_graphs() {
  return graphs_.Add();
}
inline ::example::Data_Graph* Data::add_graphs() {
  // @@protoc_insertion_point(field_add:example.Data.graphs)
  return _internal_add_graphs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::example::Data_Graph >&
Data::graphs() const {
  // @@protoc_insertion_point(field_list:example.Data.graphs)
  return graphs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace example

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_example_2eproto
