# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='instance',
  syntax='proto2',
  serialized_pb=_b('\n\x0bgraph.proto\x12\x08instance\"\x99\x01\n\x04\x44\x61ta\x12#\n\x05graph\x18\x05 \x03(\x0b\x32\x14.instance.Data.Graph\x1al\n\x05Graph\x12\r\n\x05right\x18\x01 \x02(\x05\x12(\n\x05nodes\x18\x03 \x03(\x0b\x32\x19.instance.Data.Graph.Node\x12\r\n\x05score\x18\x04 \x03(\x05\x1a\x1b\n\x04Node\x12\x13\n\x0b\x63onnectedto\x18\x02 \x03(\x05')
)




_DATA_GRAPH_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='instance.Data.Graph.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectedto', full_name='instance.Data.Graph.Node.connectedto', index=0,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=179,
)

_DATA_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='instance.Data.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='right', full_name='instance.Data.Graph.right', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='instance.Data.Graph.nodes', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='instance.Data.Graph.score', index=2,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_GRAPH_NODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=179,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='instance.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph', full_name='instance.Data.graph', index=0,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_GRAPH, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=179,
)

_DATA_GRAPH_NODE.containing_type = _DATA_GRAPH
_DATA_GRAPH.fields_by_name['nodes'].message_type = _DATA_GRAPH_NODE
_DATA_GRAPH.containing_type = _DATA
_DATA.fields_by_name['graph'].message_type = _DATA_GRAPH
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(

  Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), dict(

    Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
      DESCRIPTOR = _DATA_GRAPH_NODE,
      __module__ = 'graph_pb2'
      # @@protoc_insertion_point(class_scope:instance.Data.Graph.Node)
      ))
    ,
    DESCRIPTOR = _DATA_GRAPH,
    __module__ = 'graph_pb2'
    # @@protoc_insertion_point(class_scope:instance.Data.Graph)
    ))
  ,
  DESCRIPTOR = _DATA,
  __module__ = 'graph_pb2'
  # @@protoc_insertion_point(class_scope:instance.Data)
  ))
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.Graph)
_sym_db.RegisterMessage(Data.Graph.Node)


# @@protoc_insertion_point(module_scope)
